# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC Dev Workflow

on:
  push:
    branches:
      - feature/**
    paths:
      - "Definitions/**"
      - ".github/**"
  workflow_dispatch:

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan epac-dev
    uses: rahielorg/workflow-templates/.github/workflows/plan.yml@main
    with:
      pacEnvironmentSelector: epac-dev
      planGitHubEnvironment: EPAC-DEV
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployPolicy:
    name: Deploy epac-dev Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes'
    uses: rahielorg/workflow-templates/.github/workflows/deploy-policy.yml@main
    with:
      pacEnvironmentSelector: epac-dev
      planGitHubEnvironment: PAC-DEV
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployRoles:
    name: Deploy epac-dev Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes'
    uses: rahielorg/workflow-templates/.github/workflows/deploy-roles.yml@main
    with:
      pacEnvironmentSelector: epac-dev
      planGitHubEnvironment: PAC-DEV
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  tenantPlan:
    name: Plan tenant
    needs: [deployPolicy, deployRoles]
    if: |
      always()
      && !contains(needs.*.result,'failure')
    uses: rahielorg/workflow-templates/.github/workflows/plan.yml@main
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: TENANT-PLAN
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit